d3.select("svg")
  .selectAll("rect")
  .data([15, 50, 22, 8, 100, 10])
  .enter()
  .append("rect")
  .attr("width", 50)                      
  .attr("height", d => d)
  .style("fill","blue")
  .style("stroke", "red")
  .style("stroke-width", "1px")
  .style("opacity", .25)
  	.attr("x", (d, i) => i * 50)
  	.attr('y', d => 250 - d);
